my_palace =[
    "mailbox",
    "drive: wall",
    "pot plants by brush fence",
    "Margaret courtyard",
    "Margaret's kitchen through window",
    "Margaret's carport",
    "Frog & cumquat garden patch",
    "front door & porch",
    "living room: floor",
    "Living room: couch",
    "living room: front garden through window",
    "Living room: on tv",
    "living room: on top of the bookshelf",
    "livin room: on/in the heater",
    "living room: aquarium",
    "living room: on/in the curved-glass cabinet",
    "corridor&bookshelf",
    "My room: floor",
    "My room: storage wardrobe",
    "my room: on bed",
    "my room: look through window",
    "my room: olde clothes wardrobe",
    "my room: desk",
    "playroom: floor",
    "playroom: tool cupboard",
    "attic space",
    "playroom: toy cupboard",
    "kitchen: computer nook",
    "kitchen: dinner table",
    "kitchen: fridge",
    "kitchen: stovetop",
    "kitchen: sink",
    "kitchen: countertop",
    "kitchen: bin under sink",
    "Alison's room: floor",
    "Alison's room: terrarium",
    "toilet",
    "bathroom: floor",
    "bathroom: shower",
    "bathroom: sink & mirror cabinet",
    "Parent's bedroom(corridor and wine rack)",
    "Parent's bedroom (on the bed)",
    "Laundry: cupboard",
    "Laundry: sink",
    "Backyard courtyard",
    "Backyard worm farm & vice table",
    "Backyard pots",
    "Backyard main garden",
    "Side-of-house-alley",
    "Front yard",
    "carport & keith's door",
    "Keith's garden (over fence)",
    "Under the wattle",
    "looking down the driveway",
    "Scott st: in the road."
]
